exports.weatherDescriptions = {
    200: 'Tormenta eléctrica con lluvia ligera',
    201: 'Tormenta eléctrica con lluvia',
    202: 'Tormenta eléctrica con lluvia intensa',
    210: 'Tormenta eléctrica ligera',
    211: 'Tormenta eléctrica',
    212: 'Tormenta eléctrica intensa',
    221: 'Tormenta eléctrica irregular',
    230: 'Tormenta eléctrica con llovizna ligera',
    231: 'Tormenta eléctrica con llovizna',
    232: 'Tormenta eléctrica con llovizna intensa',
    300: 'Llovizna ligera',
    301: 'Llovizna',
    302: 'Llovizna intensa',
    310: 'Llovizna ligera con lluvia',
    311: 'Llovizna con lluvia',
    312: 'Llovizna intensa con lluvia',
    313: 'Aguacero con llovizna',
    314: 'Aguacero intenso con llovizna',
    321: 'Llovizna intermitente',
    500: 'Lluvia ligera',
    501: 'Lluvia moderada',
    502: 'Lluvia intensa',
    503: 'Lluvia muy intensa',
    504: 'Lluvia extrema',
    511: 'Lluvia helada',
    520: 'Lluvia ligera intermitente',
    521: 'Lluvia intermitente',
    522: 'Lluvia intensa intermitente',
    531: 'Lluvia irregular intermitente',
    600: 'Nieve ligera',
    601: 'Nieve',
    602: 'Nieve intensa',
    611: 'Aguanieve',
    612: 'Aguanieve ligero intermitente',
    613: 'Aguanieve intermitente',
    615: 'Lluvia y nieve ligera',
    616: 'Lluvia y nieve',
    620: 'Aguanieve ligera intermitente',
    621: 'Aguanieve intermitente',
    622: 'Aguanieve intensa intermitente',
    701: 'Niebla',
    711: 'Humo',
    721: 'Neblina',
    731: 'Polvo en suspensión',
    741: 'Niebla',
    751: 'Arena',
    761: 'Polvo',
    762: 'Ceniza volcánica',
    771: 'Chubasco',
    781: 'Tornado',
    800: 'Cielo despejado',
    801: 'Pocas nubes',
    802: 'Nubes dispersas',
    803: 'Nubes rotas',
    804: 'Cielo nublado'
};